config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/about' => 'about#index'
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/photo.rb
class Photo < ApplicationRecord
  include ImageUploader::Attachment(:image)

  validates :title, :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update)
  end 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  
 # GET /articles
  # GET /articles.json
  def index
    if params[:category].blank?
    @articles = Article.all
    else
      @category_id = Category.find_by(name: params[:category]).id
      @articles = Article.where(category_id: @category_id)
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params.merge(user: current_user))
    @article.category_id = article_params[:category_id]

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :image_url, :category_id)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :image)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/about/index.html.haml
%h1 This is a static page

app/views/articles/_form.html.haml
= form_with(model: article, local: true) do |form|
  - if article.errors.any?
    #error_explanation
      %h2
        = pluralize(article.errors.count, "error")
        prohibited this article from being saved:
      %ul
        - article.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.text_field :title, class: 'form-control', placeholder: 'Title of Article'
  .form-group
    = form.text_area :body, class: 'form-control', placeholder: 'Article Content'
  .form-group
    = form.text_field :image_url, class: 'form-control', placeholder: 'Image Location'
  .c-select
    = form.collection_select :category_id, Category.all, :id, :name, {prompt: 'Select a Category'}, class: 'form-control'
  .form-group
    = form.submit class:'btn btn-default btn-primary'

app/views/articles/edit.html.haml
%h1 Editing Article
= render 'form', article: @article
= link_to 'Show', @article
|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%p#notice= notice
- @articles.each do |article|
  %h2= link_to article.title, article
  %p= truncate(article.body,lenth: 200)
%br/
- if user_signed_in?
  = link_to 'New Article', new_article_path
- else
  = link_to 'Sign In', root_path

app/views/articles/new.html.haml
%h1 New Article
= render 'form', article: @article
= link_to 'Back', articles_path

app/views/articles/show.html.haml
%style{:media => "screen"}
  :cdata
    img {
    max-width: 100px;
    max-height: 100px;
    }
%p#notice= notice
%p
%h1= @article.title
%p
  = image_tag @article.image_url, size: '200x200', align: 'right'
  = @article.body
- if user_signed_in?
  = link_to 'Edit', edit_article_path(@article)
  |
= link_to 'Back', articles_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Wiki
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-default
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
              %a.navbar-brand{:href => root_path} Wiki 4 You

        / Collect the nav links, forms, and other content for toggling
        / JS not loaded or firing so the below line is missing..move it up
        #bs-example-navbar-collapse-1.collapse.navbar-collapse-1
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li= link_to "New Article", new_article_path, class: 'navbar-link'
              %li= link_to "Sign out", destroy_user_session_path, :method => :delete
            - else
              %li= link_to "Sign Up", new_user_registration_path
              %li= link_to "Sign In", new_user_session_path
        / /.navbar-collapse
      / /.container-fluid
    .container
      .row
        .col-lg-10
          = yield
        .col-lg-2
          %ul.nav.nav-pills.nav-stacked
            %li= link_to 'All Categories', root_path
            .col-md-2
              - Category.all.each do |cat|
                %li
                  = link_to cat.name, articles_path(category: cat.name)

app/views/photos/_form.html.haml
= form_with(model: @photo, local: true) do |form|
  - if @photo.errors.any?
    #error_explanation
      %h2
        = pluralize(@photo.errors.count, "error")
        prohibited this @photo from being saved:
      %ul
        - @photo.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :title
    = form.text_field :title, class: 'form-control'
  .form-group
    = form.label :image
    = image_tag form.object.image_url if form.object.cached_image_data
    = form.hidden_field :image, value: form.object.cached_image_data
    = form.file_field :image, class: 'form-control'
  .form-group
    - if @photo.persisted?
      .float-right
        = link_to 'Destroy', @photo, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' }
    = form.submit class: 'btn btn-primary'
    - if @photo.persisted?
      = link_to "Cancel", @photo, class: "btn btn-link"
    - else
      = link_to "Cancel", @photos_path, class: "btn btn-link"

app/views/photos/edit.html.haml
%h1 Editing photo

= render 'form'

= link_to 'Show', @photo
\|
= link_to 'Back', photos_path

app/views/photos/index.html.haml
%h1 Listing photos

%table
  %thead
    %tr
      %th Title
      %th Image data
      %th
      %th
      %th

  %tbody
    - @photos.each do |photo|
      %tr
        %td= photo.title
        %td= photo.image_data
        %td= link_to 'Show', photo
        %td= link_to 'Edit', edit_photo_path(photo)
        %td= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Photo', new_photo_path

app/views/photos/new.html.haml
%h1 New photo

= render 'form'

= link_to 'Back', photos_path

app/views/photos/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @photo.title
%p
  %b Image data:
  = @photo.image_data

= link_to 'Edit', edit_photo_path(@photo)
\|
= link_to 'Back', photos_path